### ISSUE TITLE
 TypeError: setup() got multiple values for keyword argument 'requires'

### ISSUE THREAD

**Issue by somenxavier** [tonyfischetti/sake#54]
Hi,

I get this issue 
```
Traceback (most recent call last):
  File "setup.py", line 91, in <module>
    **kw
TypeError: setup() got multiple values for keyword argument 'requires'
```

when I try to install in Arch linux. See [this](https://bbs.archlinux.org/viewtopic.php?pid=1503757#p1503757) for more info.

**Comment by kirbyfan64** [comment]
This was kind of my fault...I don't use plain distutils, so I didn't notice the error.

**Comment by somenxavier** [comment]
I don't know any word you are saying. I'm definitively a newbee. I reported the issue because they suggest me to do.

**Comment by kirbyfan64** [comment]
@somenxavier It's that Python has two distribution tools: distutils and setuptools.

Distutils is the *primary* Python package utility. I had modified Sake to allow users to use setuptools so the dependencies can be automatically downloaded. However, some change in the process must have made this not work with plain distutils. I use setuptools, so I didn't notice the error.

Short version: Python packaging horrors strike again!

You *should* probably install setuptools if you're doing anything with Python, though; a LOT of projects require it.

**Comment by somenxavier** [comment]
Thanks.

**Comment by kirbyfan64** [comment]
@somenxavier This should be fixed now; can you try again?

**Comment by somenxavier** [comment]
@kirbyfan64 I just reported the bug because they [said me](https://bbs.archlinux.org/viewtopic.php?pid=1503757#p1503757)

**Comment by tonyfischetti** [comment]
It turns out this wasn't fixed until 3605116eb3c1027ce266b13061f6fde75cf5c2cd
Thanks for the catch @somenxavier :)

**Comment by somenxavier** [comment]
Nice, @tonyfischetti
